// Code generated by ent, DO NOT EDIT.

package ruleset

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ruleset type in the database.
	Label = "ruleset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldRemote holds the string denoting the remote field in the database.
	FieldRemote = "remote"
	// FieldBinary holds the string denoting the binary field in the database.
	FieldBinary = "binary"
	// FieldDownloadDetour holds the string denoting the download_detour field in the database.
	FieldDownloadDetour = "download_detour"
	// FieldUpdateInterval holds the string denoting the update_interval field in the database.
	FieldUpdateInterval = "update_interval"
	// Table holds the table name of the ruleset in the database.
	Table = "rulesets"
)

// Columns holds all SQL columns for ruleset fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPath,
	FieldRemote,
	FieldBinary,
	FieldDownloadDetour,
	FieldUpdateInterval,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PathValidator is a validator for the "path" field. It is called by the builders before save.
	PathValidator func(string) error
	// UpdateIntervalValidator is a validator for the "update_interval" field. It is called by the builders before save.
	UpdateIntervalValidator func(string) error
)

// OrderOption defines the ordering options for the Ruleset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByRemote orders the results by the remote field.
func ByRemote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemote, opts...).ToFunc()
}

// ByBinary orders the results by the binary field.
func ByBinary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBinary, opts...).ToFunc()
}

// ByDownloadDetour orders the results by the download_detour field.
func ByDownloadDetour(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloadDetour, opts...).ToFunc()
}

// ByUpdateInterval orders the results by the update_interval field.
func ByUpdateInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateInterval, opts...).ToFunc()
}
