// Code generated by ent, DO NOT EDIT.

package ruleset

import (
	"sifu-box/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldName, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldPath, v))
}

// Remote applies equality check predicate on the "remote" field. It's identical to RemoteEQ.
func Remote(v bool) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldRemote, v))
}

// Binary applies equality check predicate on the "binary" field. It's identical to BinaryEQ.
func Binary(v bool) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldBinary, v))
}

// DownloadDetour applies equality check predicate on the "download_detour" field. It's identical to DownloadDetourEQ.
func DownloadDetour(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldDownloadDetour, v))
}

// UpdateInterval applies equality check predicate on the "update_interval" field. It's identical to UpdateIntervalEQ.
func UpdateInterval(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldUpdateInterval, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContainsFold(FieldName, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContainsFold(FieldPath, v))
}

// RemoteEQ applies the EQ predicate on the "remote" field.
func RemoteEQ(v bool) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldRemote, v))
}

// RemoteNEQ applies the NEQ predicate on the "remote" field.
func RemoteNEQ(v bool) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldRemote, v))
}

// BinaryEQ applies the EQ predicate on the "binary" field.
func BinaryEQ(v bool) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldBinary, v))
}

// BinaryNEQ applies the NEQ predicate on the "binary" field.
func BinaryNEQ(v bool) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldBinary, v))
}

// DownloadDetourEQ applies the EQ predicate on the "download_detour" field.
func DownloadDetourEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldDownloadDetour, v))
}

// DownloadDetourNEQ applies the NEQ predicate on the "download_detour" field.
func DownloadDetourNEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldDownloadDetour, v))
}

// DownloadDetourIn applies the In predicate on the "download_detour" field.
func DownloadDetourIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIn(FieldDownloadDetour, vs...))
}

// DownloadDetourNotIn applies the NotIn predicate on the "download_detour" field.
func DownloadDetourNotIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotIn(FieldDownloadDetour, vs...))
}

// DownloadDetourGT applies the GT predicate on the "download_detour" field.
func DownloadDetourGT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGT(FieldDownloadDetour, v))
}

// DownloadDetourGTE applies the GTE predicate on the "download_detour" field.
func DownloadDetourGTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGTE(FieldDownloadDetour, v))
}

// DownloadDetourLT applies the LT predicate on the "download_detour" field.
func DownloadDetourLT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLT(FieldDownloadDetour, v))
}

// DownloadDetourLTE applies the LTE predicate on the "download_detour" field.
func DownloadDetourLTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLTE(FieldDownloadDetour, v))
}

// DownloadDetourContains applies the Contains predicate on the "download_detour" field.
func DownloadDetourContains(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContains(FieldDownloadDetour, v))
}

// DownloadDetourHasPrefix applies the HasPrefix predicate on the "download_detour" field.
func DownloadDetourHasPrefix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasPrefix(FieldDownloadDetour, v))
}

// DownloadDetourHasSuffix applies the HasSuffix predicate on the "download_detour" field.
func DownloadDetourHasSuffix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasSuffix(FieldDownloadDetour, v))
}

// DownloadDetourIsNil applies the IsNil predicate on the "download_detour" field.
func DownloadDetourIsNil() predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIsNull(FieldDownloadDetour))
}

// DownloadDetourNotNil applies the NotNil predicate on the "download_detour" field.
func DownloadDetourNotNil() predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotNull(FieldDownloadDetour))
}

// DownloadDetourEqualFold applies the EqualFold predicate on the "download_detour" field.
func DownloadDetourEqualFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEqualFold(FieldDownloadDetour, v))
}

// DownloadDetourContainsFold applies the ContainsFold predicate on the "download_detour" field.
func DownloadDetourContainsFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContainsFold(FieldDownloadDetour, v))
}

// UpdateIntervalEQ applies the EQ predicate on the "update_interval" field.
func UpdateIntervalEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEQ(FieldUpdateInterval, v))
}

// UpdateIntervalNEQ applies the NEQ predicate on the "update_interval" field.
func UpdateIntervalNEQ(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNEQ(FieldUpdateInterval, v))
}

// UpdateIntervalIn applies the In predicate on the "update_interval" field.
func UpdateIntervalIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIn(FieldUpdateInterval, vs...))
}

// UpdateIntervalNotIn applies the NotIn predicate on the "update_interval" field.
func UpdateIntervalNotIn(vs ...string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotIn(FieldUpdateInterval, vs...))
}

// UpdateIntervalGT applies the GT predicate on the "update_interval" field.
func UpdateIntervalGT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGT(FieldUpdateInterval, v))
}

// UpdateIntervalGTE applies the GTE predicate on the "update_interval" field.
func UpdateIntervalGTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldGTE(FieldUpdateInterval, v))
}

// UpdateIntervalLT applies the LT predicate on the "update_interval" field.
func UpdateIntervalLT(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLT(FieldUpdateInterval, v))
}

// UpdateIntervalLTE applies the LTE predicate on the "update_interval" field.
func UpdateIntervalLTE(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldLTE(FieldUpdateInterval, v))
}

// UpdateIntervalContains applies the Contains predicate on the "update_interval" field.
func UpdateIntervalContains(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContains(FieldUpdateInterval, v))
}

// UpdateIntervalHasPrefix applies the HasPrefix predicate on the "update_interval" field.
func UpdateIntervalHasPrefix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasPrefix(FieldUpdateInterval, v))
}

// UpdateIntervalHasSuffix applies the HasSuffix predicate on the "update_interval" field.
func UpdateIntervalHasSuffix(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldHasSuffix(FieldUpdateInterval, v))
}

// UpdateIntervalIsNil applies the IsNil predicate on the "update_interval" field.
func UpdateIntervalIsNil() predicate.Ruleset {
	return predicate.Ruleset(sql.FieldIsNull(FieldUpdateInterval))
}

// UpdateIntervalNotNil applies the NotNil predicate on the "update_interval" field.
func UpdateIntervalNotNil() predicate.Ruleset {
	return predicate.Ruleset(sql.FieldNotNull(FieldUpdateInterval))
}

// UpdateIntervalEqualFold applies the EqualFold predicate on the "update_interval" field.
func UpdateIntervalEqualFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldEqualFold(FieldUpdateInterval, v))
}

// UpdateIntervalContainsFold applies the ContainsFold predicate on the "update_interval" field.
func UpdateIntervalContainsFold(v string) predicate.Ruleset {
	return predicate.Ruleset(sql.FieldContainsFold(FieldUpdateInterval, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ruleset) predicate.Ruleset {
	return predicate.Ruleset(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ruleset) predicate.Ruleset {
	return predicate.Ruleset(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ruleset) predicate.Ruleset {
	return predicate.Ruleset(sql.NotPredicates(p))
}
