// Code generated by ent, DO NOT EDIT.

package template

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the template type in the database.
	Label = "template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDNS holds the string denoting the dns field in the database.
	FieldDNS = "dns"
	// FieldLog holds the string denoting the log field in the database.
	FieldLog = "log"
	// FieldRoute holds the string denoting the route field in the database.
	FieldRoute = "route"
	// FieldInbounds holds the string denoting the inbounds field in the database.
	FieldInbounds = "inbounds"
	// FieldOutboundGroups holds the string denoting the outbound_groups field in the database.
	FieldOutboundGroups = "outbound_groups"
	// FieldNtp holds the string denoting the ntp field in the database.
	FieldNtp = "ntp"
	// FieldExperiment holds the string denoting the experiment field in the database.
	FieldExperiment = "experiment"
	// FieldProviders holds the string denoting the providers field in the database.
	FieldProviders = "providers"
	// FieldChanged holds the string denoting the changed field in the database.
	FieldChanged = "changed"
	// Table holds the table name of the template in the database.
	Table = "templates"
)

// Columns holds all SQL columns for template fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDNS,
	FieldLog,
	FieldRoute,
	FieldInbounds,
	FieldOutboundGroups,
	FieldNtp,
	FieldExperiment,
	FieldProviders,
	FieldChanged,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Template queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByChanged orders the results by the changed field.
func ByChanged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChanged, opts...).ToFunc()
}
