// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sifu-box/ent/provider"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderCreate is the builder for creating a Provider entity.
type ProviderCreate struct {
	config
	mutation *ProviderMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ProviderCreate) SetName(v string) *ProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *ProviderCreate) SetPath(v string) *ProviderCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNodes sets the "nodes" field.
func (_c *ProviderCreate) SetNodes(v []map[string]interface{}) *ProviderCreate {
	_c.mutation.SetNodes(v)
	return _c
}

// SetRemote sets the "remote" field.
func (_c *ProviderCreate) SetRemote(v bool) *ProviderCreate {
	_c.mutation.SetRemote(v)
	return _c
}

// SetUUID sets the "uuid" field.
func (_c *ProviderCreate) SetUUID(v string) *ProviderCreate {
	_c.mutation.SetUUID(v)
	return _c
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableUUID(v *string) *ProviderCreate {
	if v != nil {
		_c.SetUUID(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *ProviderCreate) SetUpdated(v bool) *ProviderCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *ProviderCreate) SetNillableUpdated(v *bool) *ProviderCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// Mutation returns the ProviderMutation object of the builder.
func (_c *ProviderCreate) Mutation() *ProviderMutation {
	return _c.mutation
}

// Save creates the Provider in the database.
func (_c *ProviderCreate) Save(ctx context.Context) (*Provider, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderCreate) SaveX(ctx context.Context) *Provider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Provider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Provider.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := provider.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Provider.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Remote(); !ok {
		return &ValidationError{Name: "remote", err: errors.New(`ent: missing required field "Provider.remote"`)}
	}
	if v, ok := _c.mutation.UUID(); ok {
		if err := provider.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "Provider.uuid": %w`, err)}
		}
	}
	return nil
}

func (_c *ProviderCreate) sqlSave(ctx context.Context) (*Provider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderCreate) createSpec() (*Provider, *sqlgraph.CreateSpec) {
	var (
		_node = &Provider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(provider.Table, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(provider.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Nodes(); ok {
		_spec.SetField(provider.FieldNodes, field.TypeJSON, value)
		_node.Nodes = value
	}
	if value, ok := _c.mutation.Remote(); ok {
		_spec.SetField(provider.FieldRemote, field.TypeBool, value)
		_node.Remote = value
	}
	if value, ok := _c.mutation.UUID(); ok {
		_spec.SetField(provider.FieldUUID, field.TypeString, value)
		_node.UUID = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(provider.FieldUpdated, field.TypeBool, value)
		_node.Updated = value
	}
	return _node, _spec
}

// ProviderCreateBulk is the builder for creating many Provider entities in bulk.
type ProviderCreateBulk struct {
	config
	err      error
	builders []*ProviderCreate
}

// Save creates the Provider entities in the database.
func (_c *ProviderCreateBulk) Save(ctx context.Context) ([]*Provider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Provider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderCreateBulk) SaveX(ctx context.Context) []*Provider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
