// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sifu-box/ent/predicate"
	"sifu-box/ent/provider"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProviderUpdate is the builder for updating Provider entities.
type ProviderUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderMutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (pu *ProviderUpdate) Where(ps ...predicate.Provider) *ProviderUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProviderUpdate) SetName(s string) *ProviderUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProviderUpdate) SetNillableName(s *string) *ProviderUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetPath sets the "path" field.
func (pu *ProviderUpdate) SetPath(s string) *ProviderUpdate {
	pu.mutation.SetPath(s)
	return pu
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (pu *ProviderUpdate) SetNillablePath(s *string) *ProviderUpdate {
	if s != nil {
		pu.SetPath(*s)
	}
	return pu
}

// SetDetour sets the "detour" field.
func (pu *ProviderUpdate) SetDetour(s string) *ProviderUpdate {
	pu.mutation.SetDetour(s)
	return pu
}

// SetNillableDetour sets the "detour" field if the given value is not nil.
func (pu *ProviderUpdate) SetNillableDetour(s *string) *ProviderUpdate {
	if s != nil {
		pu.SetDetour(*s)
	}
	return pu
}

// ClearDetour clears the value of the "detour" field.
func (pu *ProviderUpdate) ClearDetour() *ProviderUpdate {
	pu.mutation.ClearDetour()
	return pu
}

// SetRemote sets the "remote" field.
func (pu *ProviderUpdate) SetRemote(b bool) *ProviderUpdate {
	pu.mutation.SetRemote(b)
	return pu
}

// SetNillableRemote sets the "remote" field if the given value is not nil.
func (pu *ProviderUpdate) SetNillableRemote(b *bool) *ProviderUpdate {
	if b != nil {
		pu.SetRemote(*b)
	}
	return pu
}

// Mutation returns the ProviderMutation object of the builder.
func (pu *ProviderUpdate) Mutation() *ProviderMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProviderUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProviderUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProviderUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Path(); ok {
		if err := provider.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Provider.path": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Detour(); ok {
		if err := provider.DetourValidator(v); err != nil {
			return &ValidationError{Name: "detour", err: fmt.Errorf(`ent: validator failed for field "Provider.detour": %w`, err)}
		}
	}
	return nil
}

func (pu *ProviderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Path(); ok {
		_spec.SetField(provider.FieldPath, field.TypeString, value)
	}
	if value, ok := pu.mutation.Detour(); ok {
		_spec.SetField(provider.FieldDetour, field.TypeString, value)
	}
	if pu.mutation.DetourCleared() {
		_spec.ClearField(provider.FieldDetour, field.TypeString)
	}
	if value, ok := pu.mutation.Remote(); ok {
		_spec.SetField(provider.FieldRemote, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProviderUpdateOne is the builder for updating a single Provider entity.
type ProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderMutation
}

// SetName sets the "name" field.
func (puo *ProviderUpdateOne) SetName(s string) *ProviderUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProviderUpdateOne) SetNillableName(s *string) *ProviderUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetPath sets the "path" field.
func (puo *ProviderUpdateOne) SetPath(s string) *ProviderUpdateOne {
	puo.mutation.SetPath(s)
	return puo
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (puo *ProviderUpdateOne) SetNillablePath(s *string) *ProviderUpdateOne {
	if s != nil {
		puo.SetPath(*s)
	}
	return puo
}

// SetDetour sets the "detour" field.
func (puo *ProviderUpdateOne) SetDetour(s string) *ProviderUpdateOne {
	puo.mutation.SetDetour(s)
	return puo
}

// SetNillableDetour sets the "detour" field if the given value is not nil.
func (puo *ProviderUpdateOne) SetNillableDetour(s *string) *ProviderUpdateOne {
	if s != nil {
		puo.SetDetour(*s)
	}
	return puo
}

// ClearDetour clears the value of the "detour" field.
func (puo *ProviderUpdateOne) ClearDetour() *ProviderUpdateOne {
	puo.mutation.ClearDetour()
	return puo
}

// SetRemote sets the "remote" field.
func (puo *ProviderUpdateOne) SetRemote(b bool) *ProviderUpdateOne {
	puo.mutation.SetRemote(b)
	return puo
}

// SetNillableRemote sets the "remote" field if the given value is not nil.
func (puo *ProviderUpdateOne) SetNillableRemote(b *bool) *ProviderUpdateOne {
	if b != nil {
		puo.SetRemote(*b)
	}
	return puo
}

// Mutation returns the ProviderMutation object of the builder.
func (puo *ProviderUpdateOne) Mutation() *ProviderMutation {
	return puo.mutation
}

// Where appends a list predicates to the ProviderUpdate builder.
func (puo *ProviderUpdateOne) Where(ps ...predicate.Provider) *ProviderUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProviderUpdateOne) Select(field string, fields ...string) *ProviderUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Provider entity.
func (puo *ProviderUpdateOne) Save(ctx context.Context) (*Provider, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProviderUpdateOne) SaveX(ctx context.Context) *Provider {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProviderUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProviderUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := provider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Provider.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Path(); ok {
		if err := provider.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Provider.path": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Detour(); ok {
		if err := provider.DetourValidator(v); err != nil {
			return &ValidationError{Name: "detour", err: fmt.Errorf(`ent: validator failed for field "Provider.detour": %w`, err)}
		}
	}
	return nil
}

func (puo *ProviderUpdateOne) sqlSave(ctx context.Context) (_node *Provider, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(provider.Table, provider.Columns, sqlgraph.NewFieldSpec(provider.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Provider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, provider.FieldID)
		for _, f := range fields {
			if !provider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != provider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(provider.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Path(); ok {
		_spec.SetField(provider.FieldPath, field.TypeString, value)
	}
	if value, ok := puo.mutation.Detour(); ok {
		_spec.SetField(provider.FieldDetour, field.TypeString, value)
	}
	if puo.mutation.DetourCleared() {
		_spec.ClearField(provider.FieldDetour, field.TypeString)
	}
	if value, ok := puo.mutation.Remote(); ok {
		_spec.SetField(provider.FieldRemote, field.TypeBool, value)
	}
	_node = &Provider{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{provider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
