// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sifu-box/ent/predicate"
	"sifu-box/ent/ruleset"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RulesetUpdate is the builder for updating Ruleset entities.
type RulesetUpdate struct {
	config
	hooks    []Hook
	mutation *RulesetMutation
}

// Where appends a list predicates to the RulesetUpdate builder.
func (_u *RulesetUpdate) Where(ps ...predicate.Ruleset) *RulesetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RulesetUpdate) SetName(v string) *RulesetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RulesetUpdate) SetNillableName(v *string) *RulesetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RulesetUpdate) SetPath(v string) *RulesetUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RulesetUpdate) SetNillablePath(v *string) *RulesetUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetRemote sets the "remote" field.
func (_u *RulesetUpdate) SetRemote(v bool) *RulesetUpdate {
	_u.mutation.SetRemote(v)
	return _u
}

// SetNillableRemote sets the "remote" field if the given value is not nil.
func (_u *RulesetUpdate) SetNillableRemote(v *bool) *RulesetUpdate {
	if v != nil {
		_u.SetRemote(*v)
	}
	return _u
}

// SetBinary sets the "binary" field.
func (_u *RulesetUpdate) SetBinary(v bool) *RulesetUpdate {
	_u.mutation.SetBinary(v)
	return _u
}

// SetNillableBinary sets the "binary" field if the given value is not nil.
func (_u *RulesetUpdate) SetNillableBinary(v *bool) *RulesetUpdate {
	if v != nil {
		_u.SetBinary(*v)
	}
	return _u
}

// SetDownloadDetour sets the "download_detour" field.
func (_u *RulesetUpdate) SetDownloadDetour(v string) *RulesetUpdate {
	_u.mutation.SetDownloadDetour(v)
	return _u
}

// SetNillableDownloadDetour sets the "download_detour" field if the given value is not nil.
func (_u *RulesetUpdate) SetNillableDownloadDetour(v *string) *RulesetUpdate {
	if v != nil {
		_u.SetDownloadDetour(*v)
	}
	return _u
}

// ClearDownloadDetour clears the value of the "download_detour" field.
func (_u *RulesetUpdate) ClearDownloadDetour() *RulesetUpdate {
	_u.mutation.ClearDownloadDetour()
	return _u
}

// SetUpdateInterval sets the "update_interval" field.
func (_u *RulesetUpdate) SetUpdateInterval(v string) *RulesetUpdate {
	_u.mutation.SetUpdateInterval(v)
	return _u
}

// SetNillableUpdateInterval sets the "update_interval" field if the given value is not nil.
func (_u *RulesetUpdate) SetNillableUpdateInterval(v *string) *RulesetUpdate {
	if v != nil {
		_u.SetUpdateInterval(*v)
	}
	return _u
}

// ClearUpdateInterval clears the value of the "update_interval" field.
func (_u *RulesetUpdate) ClearUpdateInterval() *RulesetUpdate {
	_u.mutation.ClearUpdateInterval()
	return _u
}

// SetTemplates sets the "templates" field.
func (_u *RulesetUpdate) SetTemplates(v []string) *RulesetUpdate {
	_u.mutation.SetTemplates(v)
	return _u
}

// AppendTemplates appends value to the "templates" field.
func (_u *RulesetUpdate) AppendTemplates(v []string) *RulesetUpdate {
	_u.mutation.AppendTemplates(v)
	return _u
}

// ClearTemplates clears the value of the "templates" field.
func (_u *RulesetUpdate) ClearTemplates() *RulesetUpdate {
	_u.mutation.ClearTemplates()
	return _u
}

// Mutation returns the RulesetMutation object of the builder.
func (_u *RulesetUpdate) Mutation() *RulesetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RulesetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RulesetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RulesetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RulesetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RulesetUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := ruleset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ruleset.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := ruleset.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Ruleset.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdateInterval(); ok {
		if err := ruleset.UpdateIntervalValidator(v); err != nil {
			return &ValidationError{Name: "update_interval", err: fmt.Errorf(`ent: validator failed for field "Ruleset.update_interval": %w`, err)}
		}
	}
	return nil
}

func (_u *RulesetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ruleset.Table, ruleset.Columns, sqlgraph.NewFieldSpec(ruleset.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ruleset.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(ruleset.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remote(); ok {
		_spec.SetField(ruleset.FieldRemote, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Binary(); ok {
		_spec.SetField(ruleset.FieldBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DownloadDetour(); ok {
		_spec.SetField(ruleset.FieldDownloadDetour, field.TypeString, value)
	}
	if _u.mutation.DownloadDetourCleared() {
		_spec.ClearField(ruleset.FieldDownloadDetour, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateInterval(); ok {
		_spec.SetField(ruleset.FieldUpdateInterval, field.TypeString, value)
	}
	if _u.mutation.UpdateIntervalCleared() {
		_spec.ClearField(ruleset.FieldUpdateInterval, field.TypeString)
	}
	if value, ok := _u.mutation.Templates(); ok {
		_spec.SetField(ruleset.FieldTemplates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTemplates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ruleset.FieldTemplates, value)
		})
	}
	if _u.mutation.TemplatesCleared() {
		_spec.ClearField(ruleset.FieldTemplates, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ruleset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RulesetUpdateOne is the builder for updating a single Ruleset entity.
type RulesetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RulesetMutation
}

// SetName sets the "name" field.
func (_u *RulesetUpdateOne) SetName(v string) *RulesetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RulesetUpdateOne) SetNillableName(v *string) *RulesetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *RulesetUpdateOne) SetPath(v string) *RulesetUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *RulesetUpdateOne) SetNillablePath(v *string) *RulesetUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetRemote sets the "remote" field.
func (_u *RulesetUpdateOne) SetRemote(v bool) *RulesetUpdateOne {
	_u.mutation.SetRemote(v)
	return _u
}

// SetNillableRemote sets the "remote" field if the given value is not nil.
func (_u *RulesetUpdateOne) SetNillableRemote(v *bool) *RulesetUpdateOne {
	if v != nil {
		_u.SetRemote(*v)
	}
	return _u
}

// SetBinary sets the "binary" field.
func (_u *RulesetUpdateOne) SetBinary(v bool) *RulesetUpdateOne {
	_u.mutation.SetBinary(v)
	return _u
}

// SetNillableBinary sets the "binary" field if the given value is not nil.
func (_u *RulesetUpdateOne) SetNillableBinary(v *bool) *RulesetUpdateOne {
	if v != nil {
		_u.SetBinary(*v)
	}
	return _u
}

// SetDownloadDetour sets the "download_detour" field.
func (_u *RulesetUpdateOne) SetDownloadDetour(v string) *RulesetUpdateOne {
	_u.mutation.SetDownloadDetour(v)
	return _u
}

// SetNillableDownloadDetour sets the "download_detour" field if the given value is not nil.
func (_u *RulesetUpdateOne) SetNillableDownloadDetour(v *string) *RulesetUpdateOne {
	if v != nil {
		_u.SetDownloadDetour(*v)
	}
	return _u
}

// ClearDownloadDetour clears the value of the "download_detour" field.
func (_u *RulesetUpdateOne) ClearDownloadDetour() *RulesetUpdateOne {
	_u.mutation.ClearDownloadDetour()
	return _u
}

// SetUpdateInterval sets the "update_interval" field.
func (_u *RulesetUpdateOne) SetUpdateInterval(v string) *RulesetUpdateOne {
	_u.mutation.SetUpdateInterval(v)
	return _u
}

// SetNillableUpdateInterval sets the "update_interval" field if the given value is not nil.
func (_u *RulesetUpdateOne) SetNillableUpdateInterval(v *string) *RulesetUpdateOne {
	if v != nil {
		_u.SetUpdateInterval(*v)
	}
	return _u
}

// ClearUpdateInterval clears the value of the "update_interval" field.
func (_u *RulesetUpdateOne) ClearUpdateInterval() *RulesetUpdateOne {
	_u.mutation.ClearUpdateInterval()
	return _u
}

// SetTemplates sets the "templates" field.
func (_u *RulesetUpdateOne) SetTemplates(v []string) *RulesetUpdateOne {
	_u.mutation.SetTemplates(v)
	return _u
}

// AppendTemplates appends value to the "templates" field.
func (_u *RulesetUpdateOne) AppendTemplates(v []string) *RulesetUpdateOne {
	_u.mutation.AppendTemplates(v)
	return _u
}

// ClearTemplates clears the value of the "templates" field.
func (_u *RulesetUpdateOne) ClearTemplates() *RulesetUpdateOne {
	_u.mutation.ClearTemplates()
	return _u
}

// Mutation returns the RulesetMutation object of the builder.
func (_u *RulesetUpdateOne) Mutation() *RulesetMutation {
	return _u.mutation
}

// Where appends a list predicates to the RulesetUpdate builder.
func (_u *RulesetUpdateOne) Where(ps ...predicate.Ruleset) *RulesetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RulesetUpdateOne) Select(field string, fields ...string) *RulesetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ruleset entity.
func (_u *RulesetUpdateOne) Save(ctx context.Context) (*Ruleset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RulesetUpdateOne) SaveX(ctx context.Context) *Ruleset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RulesetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RulesetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RulesetUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := ruleset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ruleset.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := ruleset.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Ruleset.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdateInterval(); ok {
		if err := ruleset.UpdateIntervalValidator(v); err != nil {
			return &ValidationError{Name: "update_interval", err: fmt.Errorf(`ent: validator failed for field "Ruleset.update_interval": %w`, err)}
		}
	}
	return nil
}

func (_u *RulesetUpdateOne) sqlSave(ctx context.Context) (_node *Ruleset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ruleset.Table, ruleset.Columns, sqlgraph.NewFieldSpec(ruleset.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ruleset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ruleset.FieldID)
		for _, f := range fields {
			if !ruleset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ruleset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ruleset.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(ruleset.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Remote(); ok {
		_spec.SetField(ruleset.FieldRemote, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Binary(); ok {
		_spec.SetField(ruleset.FieldBinary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DownloadDetour(); ok {
		_spec.SetField(ruleset.FieldDownloadDetour, field.TypeString, value)
	}
	if _u.mutation.DownloadDetourCleared() {
		_spec.ClearField(ruleset.FieldDownloadDetour, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateInterval(); ok {
		_spec.SetField(ruleset.FieldUpdateInterval, field.TypeString, value)
	}
	if _u.mutation.UpdateIntervalCleared() {
		_spec.ClearField(ruleset.FieldUpdateInterval, field.TypeString)
	}
	if value, ok := _u.mutation.Templates(); ok {
		_spec.SetField(ruleset.FieldTemplates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTemplates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ruleset.FieldTemplates, value)
		})
	}
	if _u.mutation.TemplatesCleared() {
		_spec.ClearField(ruleset.FieldTemplates, field.TypeJSON)
	}
	_node = &Ruleset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ruleset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
