// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sifu-box/ent/ruleset"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RulesetCreate is the builder for creating a Ruleset entity.
type RulesetCreate struct {
	config
	mutation *RulesetMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RulesetCreate) SetName(v string) *RulesetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *RulesetCreate) SetPath(v string) *RulesetCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetRemote sets the "remote" field.
func (_c *RulesetCreate) SetRemote(v bool) *RulesetCreate {
	_c.mutation.SetRemote(v)
	return _c
}

// SetBinary sets the "binary" field.
func (_c *RulesetCreate) SetBinary(v bool) *RulesetCreate {
	_c.mutation.SetBinary(v)
	return _c
}

// SetDownloadDetour sets the "download_detour" field.
func (_c *RulesetCreate) SetDownloadDetour(v string) *RulesetCreate {
	_c.mutation.SetDownloadDetour(v)
	return _c
}

// SetNillableDownloadDetour sets the "download_detour" field if the given value is not nil.
func (_c *RulesetCreate) SetNillableDownloadDetour(v *string) *RulesetCreate {
	if v != nil {
		_c.SetDownloadDetour(*v)
	}
	return _c
}

// SetUpdateInterval sets the "update_interval" field.
func (_c *RulesetCreate) SetUpdateInterval(v string) *RulesetCreate {
	_c.mutation.SetUpdateInterval(v)
	return _c
}

// SetNillableUpdateInterval sets the "update_interval" field if the given value is not nil.
func (_c *RulesetCreate) SetNillableUpdateInterval(v *string) *RulesetCreate {
	if v != nil {
		_c.SetUpdateInterval(*v)
	}
	return _c
}

// SetTemplates sets the "templates" field.
func (_c *RulesetCreate) SetTemplates(v []string) *RulesetCreate {
	_c.mutation.SetTemplates(v)
	return _c
}

// Mutation returns the RulesetMutation object of the builder.
func (_c *RulesetCreate) Mutation() *RulesetMutation {
	return _c.mutation
}

// Save creates the Ruleset in the database.
func (_c *RulesetCreate) Save(ctx context.Context) (*Ruleset, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RulesetCreate) SaveX(ctx context.Context) *Ruleset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RulesetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RulesetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RulesetCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Ruleset.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := ruleset.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Ruleset.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Ruleset.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := ruleset.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Ruleset.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Remote(); !ok {
		return &ValidationError{Name: "remote", err: errors.New(`ent: missing required field "Ruleset.remote"`)}
	}
	if _, ok := _c.mutation.Binary(); !ok {
		return &ValidationError{Name: "binary", err: errors.New(`ent: missing required field "Ruleset.binary"`)}
	}
	if v, ok := _c.mutation.UpdateInterval(); ok {
		if err := ruleset.UpdateIntervalValidator(v); err != nil {
			return &ValidationError{Name: "update_interval", err: fmt.Errorf(`ent: validator failed for field "Ruleset.update_interval": %w`, err)}
		}
	}
	return nil
}

func (_c *RulesetCreate) sqlSave(ctx context.Context) (*Ruleset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RulesetCreate) createSpec() (*Ruleset, *sqlgraph.CreateSpec) {
	var (
		_node = &Ruleset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ruleset.Table, sqlgraph.NewFieldSpec(ruleset.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ruleset.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(ruleset.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Remote(); ok {
		_spec.SetField(ruleset.FieldRemote, field.TypeBool, value)
		_node.Remote = value
	}
	if value, ok := _c.mutation.Binary(); ok {
		_spec.SetField(ruleset.FieldBinary, field.TypeBool, value)
		_node.Binary = value
	}
	if value, ok := _c.mutation.DownloadDetour(); ok {
		_spec.SetField(ruleset.FieldDownloadDetour, field.TypeString, value)
		_node.DownloadDetour = value
	}
	if value, ok := _c.mutation.UpdateInterval(); ok {
		_spec.SetField(ruleset.FieldUpdateInterval, field.TypeString, value)
		_node.UpdateInterval = value
	}
	if value, ok := _c.mutation.Templates(); ok {
		_spec.SetField(ruleset.FieldTemplates, field.TypeJSON, value)
		_node.Templates = value
	}
	return _node, _spec
}

// RulesetCreateBulk is the builder for creating many Ruleset entities in bulk.
type RulesetCreateBulk struct {
	config
	err      error
	builders []*RulesetCreate
}

// Save creates the Ruleset entities in the database.
func (_c *RulesetCreateBulk) Save(ctx context.Context) ([]*Ruleset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ruleset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RulesetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RulesetCreateBulk) SaveX(ctx context.Context) []*Ruleset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RulesetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RulesetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
