// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"sifu-box/ent/ruleset"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Ruleset is the model entity for the Ruleset schema.
type Ruleset struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Remote holds the value of the "remote" field.
	Remote bool `json:"remote,omitempty"`
	// Binary holds the value of the "binary" field.
	Binary bool `json:"binary,omitempty"`
	// DownloadDetour holds the value of the "download_detour" field.
	DownloadDetour string `json:"download_detour,omitempty"`
	// UpdateInterval holds the value of the "update_interval" field.
	UpdateInterval string `json:"update_interval,omitempty"`
	// Templates holds the value of the "templates" field.
	Templates    []string `json:"templates,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ruleset) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ruleset.FieldTemplates:
			values[i] = new([]byte)
		case ruleset.FieldRemote, ruleset.FieldBinary:
			values[i] = new(sql.NullBool)
		case ruleset.FieldID:
			values[i] = new(sql.NullInt64)
		case ruleset.FieldName, ruleset.FieldPath, ruleset.FieldDownloadDetour, ruleset.FieldUpdateInterval:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ruleset fields.
func (_m *Ruleset) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ruleset.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ruleset.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case ruleset.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case ruleset.FieldRemote:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field remote", values[i])
			} else if value.Valid {
				_m.Remote = value.Bool
			}
		case ruleset.FieldBinary:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field binary", values[i])
			} else if value.Valid {
				_m.Binary = value.Bool
			}
		case ruleset.FieldDownloadDetour:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field download_detour", values[i])
			} else if value.Valid {
				_m.DownloadDetour = value.String
			}
		case ruleset.FieldUpdateInterval:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field update_interval", values[i])
			} else if value.Valid {
				_m.UpdateInterval = value.String
			}
		case ruleset.FieldTemplates:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field templates", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Templates); err != nil {
					return fmt.Errorf("unmarshal field templates: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ruleset.
// This includes values selected through modifiers, order, etc.
func (_m *Ruleset) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Ruleset.
// Note that you need to call Ruleset.Unwrap() before calling this method if this Ruleset
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ruleset) Update() *RulesetUpdateOne {
	return NewRulesetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ruleset entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ruleset) Unwrap() *Ruleset {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ruleset is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ruleset) String() string {
	var builder strings.Builder
	builder.WriteString("Ruleset(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("remote=")
	builder.WriteString(fmt.Sprintf("%v", _m.Remote))
	builder.WriteString(", ")
	builder.WriteString("binary=")
	builder.WriteString(fmt.Sprintf("%v", _m.Binary))
	builder.WriteString(", ")
	builder.WriteString("download_detour=")
	builder.WriteString(_m.DownloadDetour)
	builder.WriteString(", ")
	builder.WriteString("update_interval=")
	builder.WriteString(_m.UpdateInterval)
	builder.WriteString(", ")
	builder.WriteString("templates=")
	builder.WriteString(fmt.Sprintf("%v", _m.Templates))
	builder.WriteByte(')')
	return builder.String()
}

// Rulesets is a parsable slice of Ruleset.
type Rulesets []*Ruleset
