// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sifu-box/ent/predicate"
	"sifu-box/ent/ruleset"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RuleSetDelete is the builder for deleting a RuleSet entity.
type RuleSetDelete struct {
	config
	hooks    []Hook
	mutation *RuleSetMutation
}

// Where appends a list predicates to the RuleSetDelete builder.
func (rsd *RuleSetDelete) Where(ps ...predicate.RuleSet) *RuleSetDelete {
	rsd.mutation.Where(ps...)
	return rsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rsd *RuleSetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rsd.sqlExec, rsd.mutation, rsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rsd *RuleSetDelete) ExecX(ctx context.Context) int {
	n, err := rsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rsd *RuleSetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ruleset.Table, sqlgraph.NewFieldSpec(ruleset.FieldID, field.TypeInt))
	if ps := rsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rsd.mutation.done = true
	return affected, err
}

// RuleSetDeleteOne is the builder for deleting a single RuleSet entity.
type RuleSetDeleteOne struct {
	rsd *RuleSetDelete
}

// Where appends a list predicates to the RuleSetDelete builder.
func (rsdo *RuleSetDeleteOne) Where(ps ...predicate.RuleSet) *RuleSetDeleteOne {
	rsdo.rsd.mutation.Where(ps...)
	return rsdo
}

// Exec executes the deletion query.
func (rsdo *RuleSetDeleteOne) Exec(ctx context.Context) error {
	n, err := rsdo.rsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ruleset.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rsdo *RuleSetDeleteOne) ExecX(ctx context.Context) {
	if err := rsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
