// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sifu-box/ent/provider"
	"sifu-box/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	providerFields := schema.Provider{}.Fields()
	_ = providerFields
	// providerDescName is the schema descriptor for name field.
	providerDescName := providerFields[0].Descriptor()
	// provider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	provider.NameValidator = func() func(string) error {
		validators := providerDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// providerDescPath is the schema descriptor for path field.
	providerDescPath := providerFields[1].Descriptor()
	// provider.PathValidator is a validator for the "path" field. It is called by the builders before save.
	provider.PathValidator = func() func(string) error {
		validators := providerDescPath.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(_path string) error {
			for _, fn := range fns {
				if err := fn(_path); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// providerDescDetour is the schema descriptor for detour field.
	providerDescDetour := providerFields[2].Descriptor()
	// provider.DetourValidator is a validator for the "detour" field. It is called by the builders before save.
	provider.DetourValidator = providerDescDetour.Validators[0].(func(string) error)
}
