// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	config1 "sifu-box/config"
	"sifu-box/ent/template"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Template is the model entity for the Template schema.
type Template struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// DNS holds the value of the "dns" field.
	DNS config1.DNS `json:"dns,omitempty"`
	// Log holds the value of the "log" field.
	Log config1.Log `json:"log,omitempty"`
	// Route holds the value of the "route" field.
	Route config1.Route `json:"route,omitempty"`
	// Inbounds holds the value of the "inbounds" field.
	Inbounds []config1.Inbound `json:"inbounds,omitempty"`
	// OutboundGroups holds the value of the "outbound_groups" field.
	OutboundGroups []config1.OutboundGroup `json:"outbound_groups,omitempty"`
	// Ntp holds the value of the "ntp" field.
	Ntp config1.Ntp `json:"ntp,omitempty"`
	// Experiment holds the value of the "experiment" field.
	Experiment config1.Experiment `json:"experiment,omitempty"`
	// Providers holds the value of the "providers" field.
	Providers    []string `json:"providers,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Template) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case template.FieldDNS, template.FieldLog, template.FieldRoute, template.FieldInbounds, template.FieldOutboundGroups, template.FieldNtp, template.FieldExperiment, template.FieldProviders:
			values[i] = new([]byte)
		case template.FieldID:
			values[i] = new(sql.NullInt64)
		case template.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Template fields.
func (_m *Template) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case template.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case template.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case template.FieldDNS:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dns", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DNS); err != nil {
					return fmt.Errorf("unmarshal field dns: %w", err)
				}
			}
		case template.FieldLog:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field log", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Log); err != nil {
					return fmt.Errorf("unmarshal field log: %w", err)
				}
			}
		case template.FieldRoute:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field route", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Route); err != nil {
					return fmt.Errorf("unmarshal field route: %w", err)
				}
			}
		case template.FieldInbounds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field inbounds", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Inbounds); err != nil {
					return fmt.Errorf("unmarshal field inbounds: %w", err)
				}
			}
		case template.FieldOutboundGroups:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field outbound_groups", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.OutboundGroups); err != nil {
					return fmt.Errorf("unmarshal field outbound_groups: %w", err)
				}
			}
		case template.FieldNtp:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ntp", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Ntp); err != nil {
					return fmt.Errorf("unmarshal field ntp: %w", err)
				}
			}
		case template.FieldExperiment:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field experiment", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Experiment); err != nil {
					return fmt.Errorf("unmarshal field experiment: %w", err)
				}
			}
		case template.FieldProviders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field providers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Providers); err != nil {
					return fmt.Errorf("unmarshal field providers: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Template.
// This includes values selected through modifiers, order, etc.
func (_m *Template) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Template.
// Note that you need to call Template.Unwrap() before calling this method if this Template
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Template) Update() *TemplateUpdateOne {
	return NewTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Template entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Template) Unwrap() *Template {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Template is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Template) String() string {
	var builder strings.Builder
	builder.WriteString("Template(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("dns=")
	builder.WriteString(fmt.Sprintf("%v", _m.DNS))
	builder.WriteString(", ")
	builder.WriteString("log=")
	builder.WriteString(fmt.Sprintf("%v", _m.Log))
	builder.WriteString(", ")
	builder.WriteString("route=")
	builder.WriteString(fmt.Sprintf("%v", _m.Route))
	builder.WriteString(", ")
	builder.WriteString("inbounds=")
	builder.WriteString(fmt.Sprintf("%v", _m.Inbounds))
	builder.WriteString(", ")
	builder.WriteString("outbound_groups=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutboundGroups))
	builder.WriteString(", ")
	builder.WriteString("ntp=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ntp))
	builder.WriteString(", ")
	builder.WriteString("experiment=")
	builder.WriteString(fmt.Sprintf("%v", _m.Experiment))
	builder.WriteString(", ")
	builder.WriteString("providers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Providers))
	builder.WriteByte(')')
	return builder.String()
}

// Templates is a parsable slice of Template.
type Templates []*Template
