// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sifu-box/ent/template"
	"sifu-box/singbox"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TemplateCreate is the builder for creating a Template entity.
type TemplateCreate struct {
	config
	mutation *TemplateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TemplateCreate) SetName(v string) *TemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDNS sets the "dns" field.
func (_c *TemplateCreate) SetDNS(v singbox.DNS) *TemplateCreate {
	_c.mutation.SetDNS(v)
	return _c
}

// SetNillableDNS sets the "dns" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableDNS(v *singbox.DNS) *TemplateCreate {
	if v != nil {
		_c.SetDNS(*v)
	}
	return _c
}

// SetLog sets the "log" field.
func (_c *TemplateCreate) SetLog(v singbox.Log) *TemplateCreate {
	_c.mutation.SetLog(v)
	return _c
}

// SetNillableLog sets the "log" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableLog(v *singbox.Log) *TemplateCreate {
	if v != nil {
		_c.SetLog(*v)
	}
	return _c
}

// SetRoute sets the "route" field.
func (_c *TemplateCreate) SetRoute(v singbox.Route) *TemplateCreate {
	_c.mutation.SetRoute(v)
	return _c
}

// SetNillableRoute sets the "route" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableRoute(v *singbox.Route) *TemplateCreate {
	if v != nil {
		_c.SetRoute(*v)
	}
	return _c
}

// SetInbounds sets the "inbounds" field.
func (_c *TemplateCreate) SetInbounds(v []singbox.Inbound) *TemplateCreate {
	_c.mutation.SetInbounds(v)
	return _c
}

// SetOutboundGroups sets the "outbound_groups" field.
func (_c *TemplateCreate) SetOutboundGroups(v []singbox.OutboundGroup) *TemplateCreate {
	_c.mutation.SetOutboundGroups(v)
	return _c
}

// SetNtp sets the "ntp" field.
func (_c *TemplateCreate) SetNtp(v singbox.Ntp) *TemplateCreate {
	_c.mutation.SetNtp(v)
	return _c
}

// SetNillableNtp sets the "ntp" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableNtp(v *singbox.Ntp) *TemplateCreate {
	if v != nil {
		_c.SetNtp(*v)
	}
	return _c
}

// SetExperiment sets the "experiment" field.
func (_c *TemplateCreate) SetExperiment(v singbox.Experiment) *TemplateCreate {
	_c.mutation.SetExperiment(v)
	return _c
}

// SetNillableExperiment sets the "experiment" field if the given value is not nil.
func (_c *TemplateCreate) SetNillableExperiment(v *singbox.Experiment) *TemplateCreate {
	if v != nil {
		_c.SetExperiment(*v)
	}
	return _c
}

// SetProviders sets the "providers" field.
func (_c *TemplateCreate) SetProviders(v []string) *TemplateCreate {
	_c.mutation.SetProviders(v)
	return _c
}

// Mutation returns the TemplateMutation object of the builder.
func (_c *TemplateCreate) Mutation() *TemplateMutation {
	return _c.mutation
}

// Save creates the Template in the database.
func (_c *TemplateCreate) Save(ctx context.Context) (*Template, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TemplateCreate) SaveX(ctx context.Context) *Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Template.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := template.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Template.name": %w`, err)}
		}
	}
	return nil
}

func (_c *TemplateCreate) sqlSave(ctx context.Context) (*Template, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TemplateCreate) createSpec() (*Template, *sqlgraph.CreateSpec) {
	var (
		_node = &Template{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(template.Table, sqlgraph.NewFieldSpec(template.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(template.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DNS(); ok {
		_spec.SetField(template.FieldDNS, field.TypeJSON, value)
		_node.DNS = value
	}
	if value, ok := _c.mutation.Log(); ok {
		_spec.SetField(template.FieldLog, field.TypeJSON, value)
		_node.Log = value
	}
	if value, ok := _c.mutation.Route(); ok {
		_spec.SetField(template.FieldRoute, field.TypeJSON, value)
		_node.Route = value
	}
	if value, ok := _c.mutation.Inbounds(); ok {
		_spec.SetField(template.FieldInbounds, field.TypeJSON, value)
		_node.Inbounds = value
	}
	if value, ok := _c.mutation.OutboundGroups(); ok {
		_spec.SetField(template.FieldOutboundGroups, field.TypeJSON, value)
		_node.OutboundGroups = value
	}
	if value, ok := _c.mutation.Ntp(); ok {
		_spec.SetField(template.FieldNtp, field.TypeJSON, value)
		_node.Ntp = value
	}
	if value, ok := _c.mutation.Experiment(); ok {
		_spec.SetField(template.FieldExperiment, field.TypeJSON, value)
		_node.Experiment = value
	}
	if value, ok := _c.mutation.Providers(); ok {
		_spec.SetField(template.FieldProviders, field.TypeJSON, value)
		_node.Providers = value
	}
	return _node, _spec
}

// TemplateCreateBulk is the builder for creating many Template entities in bulk.
type TemplateCreateBulk struct {
	config
	err      error
	builders []*TemplateCreate
}

// Save creates the Template entities in the database.
func (_c *TemplateCreateBulk) Save(ctx context.Context) ([]*Template, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Template, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TemplateCreateBulk) SaveX(ctx context.Context) []*Template {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
