package models

const SIFUBOXSETTINGKEY = "setting:sifubox"
const DEFAULTTEMPLATEKEY = "template:default"
const SINGBOXSETTINGKEY = "setting:singbox"
const DEFAULTTEMPLATEPATH = "default.template.yaml"
const STATICDIR = "static"
const TEMPLATEDIR = "template"
const CONFIGDIR = "config"
const SIFUBOXSETTINGFILE = "setting.config.yaml"
const SINGBOXSETTINGFILE = "singbox.config.yaml"
const TEMPDIR = "temp"
const SINGBOXCONFIGFILEDIR = "config"
const SINGBOXBACKUPCONFIGFILE = "config.json.bak"
const BACKUPDIR = "backup"
const BOOTCOMMAND = "boot_command"
const RELOADCOMMAND = "reload_command"
const STOPCOMMAND = "stop_command"
const RESTARTCOMMAND = "restart_command"
const CHECKCOMMAND = "check_command"