// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// RuleSet is the predicate function for ruleset builders.
type RuleSet func(*sql.Selector)

// Template is the predicate function for template builders.
type Template func(*sql.Selector)
